# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_fee',
            name='admission_fee',
            field=models.CharField(max_length=20),
        ),
    ]
