# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-17 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_window', models.TextField(max_length=200)),
            ],
        ),
    ]
