# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_skill', models.CharField(max_length=100)),
                ('job_description', models.TextField(max_length=1000)),
                ('experience', models.IntegerField(max_length=20)),
                ('employeement_type', models.CharField(max_length=20)),
                ('number_of_vacancy', models.IntegerField(max_length=20)),
            ],
        ),
    ]
