# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('mobile_no', models.IntegerField(max_length=20, unique=True)),
                ('user_type', models.CharField(default='admin', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='admission_fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_fee', models.IntegerField(max_length=100)),
                ('monthly_fee', models.IntegerField(max_length=100)),
                ('bus_fee', models.IntegerField(max_length=100)),
                ('extra_curricular_activities_fee', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='admissionform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('father_mobile_number', models.CharField(max_length=10, unique=True)),
                ('father_email_id', models.EmailField(max_length=20, unique=True)),
                ('mother_name', models.CharField(max_length=20)),
                ('mother_mobile_number', models.CharField(max_length=10, unique=True)),
                ('mother_email_id', models.EmailField(max_length=20, unique=True)),
                ('board_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_system.board')),
                ('standard_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_system.standard')),
            ],
        ),
        migrations.CreateModel(
            name='applicationForm_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('Email_id', models.EmailField(max_length=20, unique=True)),
                ('mobile_no', models.IntegerField(max_length=20, unique=True)),
                ('qualification', models.CharField(max_length=10)),
                ('experience', models.IntegerField(max_length=10)),
                ('current_salary', models.IntegerField(max_length=10)),
                ('excepted_salary', models.IntegerField(max_length=10)),
                ('resume', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_skill', models.CharField(max_length=100)),
                ('job_description', models.TextField(max_length=1000)),
                ('experience', models.IntegerField(max_length=10)),
                ('employeement_type', models.CharField(max_length=20)),
                ('number_of_vacancy', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='extra_curricular_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_curricular_activities_types', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='faculty_registration',
            name='experience',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='mobile_no',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_window',
            field=models.TextField(max_length=1000),
        ),
        migrations.AddField(
            model_name='admission_fee',
            name='extra_curricular_activities_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_system.extra_curricular_activities'),
        ),
        migrations.AddField(
            model_name='admission_fee',
            name='standard_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_system.standard'),
        ),
    ]
