# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_registration',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
