# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_system', '0002_auto_20190709_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_fee',
            name='monthly_fee',
            field=models.CharField(max_length=20),
        ),
    ]
