# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_system', '0002_auto_20190619_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_registration',
            name='user_type',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
