# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_system', '0003_auto_20190709_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_fee',
            name='admission_fee',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admission_fee',
            name='bus_fee',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admission_fee',
            name='monthly_fee',
            field=models.IntegerField(max_length=100),
        ),
    ]
