# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_system', '0003_auto_20190620_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_window',
            field=models.TextField(),
        ),
    ]
