from .faculty_Registration import *
from .student_Info import *
from .contact_us import *
from .standard import *
from .board import *
from .issue import *
from .notification import *
from .admin_Registration import *
from .admission_fee import *
from .admissionform import *
from .career import *
